# A composition of services that are needed to run the tests of the client
# This is for DEVELOPMENT, not production

version: "3"
services:
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - ${ID_DAO_IPFS_PORT}:5001

  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - ${ID_DAO_GANACHE_PORT}:8545
    command: --gasLimit 10000000 --mnemonic ${ID_DAO_DEV_MNEMONIC}
